[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "echo 'Checking public directory...'",
  "ls -la public/static/ || echo 'Static directory not found!'"
]

[start]
cmd = "npm start"
